# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

# Slurm configuration
partition: ou_bcs_low
gpus_per_node: 1
cpus_per_task: 8
mem_gb: 100
timeout_min: 720  # 12 hours

# Submitit settings
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
array_parallelism: 16  # Maximum number of concurrent jobs
nodes: 1
tasks_per_node: 1
max_num_timeout: 3

additional_parameters:
  mail-type: END,FAIL
  mail-user: opitcho@mit.edu


